move_group:
 ros__parameters:
  robot_description_planning:
   joint_limits:
    j1_joint:
     has_acceleration_limits: true
     max_acceleration:  13.4476451083209
     has_deceleration_limits: true
     max_deceleration: -13.4476451083209
    j2_joint:
     has_acceleration_limits: true
     max_acceleration:  9.78909460091007
     has_deceleration_limits: true
     max_deceleration: -9.78909460091007
    j3_joint:
     has_acceleration_limits: true
     max_acceleration:  21.7535435575779
     has_deceleration_limits: true
     max_deceleration: -21.7535435575779
    j4_joint:
     has_acceleration_limits: true
     max_acceleration:  42.507771590364
     has_deceleration_limits: true
     max_deceleration: -42.507771590364
    j5_joint:
     has_acceleration_limits: true
     max_acceleration:  51.8018121534037
     has_deceleration_limits: true
     max_deceleration: -49.2117215457335
    j6_joint:
     has_acceleration_limits: true
     max_acceleration:  327.270420680297
     has_deceleration_limits: true
     max_deceleration: -327.270420680297
