move_group:
 ros__parameters:
  robot_description_planning:
   joint_limits:
     j1_joint:
      has_acceleration_limits: true
      max_acceleration:  46.3207933188995
      has_deceleration_limits: true
      max_deceleration: -46.3207933188995
     j2_joint:
      has_acceleration_limits: true
      max_acceleration:  67.05173834547
      has_deceleration_limits: true
      max_deceleration: -67.05173834547
     j3_joint:
      has_acceleration_limits: true
      max_acceleration:  29.5257568359375
      has_deceleration_limits: true
      max_deceleration: -29.5257568359375
     j4_joint:
      has_acceleration_limits: true
      max_acceleration:  409.252337066505
      has_deceleration_limits: true
      max_deceleration: -409.252337066505
