move_group:
 ros__parameters:
  robot_description_planning:
   joint_limits:
    j1_joint:
     has_acceleration_limits: true
     max_acceleration:  17.6064538733016
     has_deceleration_limits: true
     max_deceleration: -17.6064538733016
    j2_joint:
     has_acceleration_limits: true
     max_acceleration:  23.3930960502106
     has_deceleration_limits: true
     max_deceleration: -23.3930960502106
    j3_joint:
     has_acceleration_limits: true
     max_acceleration:  36.1663851739155
     has_deceleration_limits: true
     max_deceleration: -36.1663851739155
    j4_joint:
     has_acceleration_limits: true
     max_acceleration:  42.507771590364
     has_deceleration_limits: true
     max_deceleration: -42.507771590364
    j5_joint:
     has_acceleration_limits: true
     max_acceleration:  51.8018121534037
     has_deceleration_limits: true
     max_deceleration: -51.8018121534037
    j6_joint:
     has_acceleration_limits: true
     max_acceleration:  327.270420680297
     has_deceleration_limits: true
     max_deceleration: -327.270420680297
